import Foundation
#if canImport(AppKit)
import AppKit
#endif
#if canImport(UIKit)
import UIKit
#endif
#if canImport(SwiftUI)
import SwiftUI
#endif
#if canImport(DeveloperToolsSupport)
import DeveloperToolsSupport
#endif

// MARK: this is generated by SwiftGen:

/// `ChromaticIcons` have enabled setting "renderingMode: alwaysTemplate" in assets file, so
/// you don't need to write `image.renderingMode(.template)` in code
public enum ChromaticIcons {
    internal static let assetBundlePath: String = currentBundle.path(forResource: "ChromaticIconsBundle", ofType: "bundle")!
    internal static let assetBundle: Bundle = Bundle(path: assetBundlePath)!
}

extension ChromaticIcons {
    public static let addCircleBoldStreamlineUltimate = ImageAsset(name: "Add-Circle-Bold--Streamline-Ultimate", bundle: assetBundle).image
}

#if os(OSX)
  public import AppKit.NSImage
  public typealias AssetColorTypeAlias = NSColor
  public typealias AssetImageTypeAlias = NSImage
#elseif os(iOS) || os(tvOS) || os(watchOS)
  public import UIKit.UIImage
  public typealias AssetColorTypeAlias = UIColor
  public typealias AssetImageTypeAlias = UIImage
#endif

import SwiftUI

public struct ImageAsset {
  public let name: String
  public let bundle: Bundle

  public var image: AssetImageTypeAlias {
    #if os(iOS) || os(tvOS)
    let image = AssetImageTypeAlias(named: name, in: bundle, compatibleWith: nil)
    #elseif os(OSX)
    let image = bundle.image(forResource: NSImage.Name(name))
    #elseif os(watchOS)
    let image = AssetImageTypeAlias(named: name)
    #endif
    guard let result = image else { fatalError("Unable to load image named \(name).") }
    return result
  }

  public var swiftUIImage: Image { Image(name, bundle: bundle) }
}

public extension AssetImageTypeAlias {
  @available(OSX, deprecated,
    message: "This initializer is unsafe on macOS, please use the ImageAsset.image property")
  convenience init!(asset: ImageAsset) {
    #if os(iOS) || os(tvOS)
    let bundle = asset.bundle
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(OSX)
    self.init(named: NSImage.Name(asset.name))
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

fileprivate let currentBundle = Bundle(for: BundleToken.self)

private final class BundleToken {}
